site_name: 'King & McGaw Developers'
site_description: 'The King & McGaw Developers Blog'
site_author: 'King & McGaw'
site_url: '/'
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:year/:month/:day/:title
paginate: 5
